In [3]:
import pandas as pd 
import numpy as np

In [8]:
df = pd.read_csv('C:/Users/lab1/Desktop/ECGANALYSIS/Final-Year-Project-main/Dataset/vitals_dataset.csv')
df.head(50)

     ECG_value  Temperature_C       SpO2   Pulse_bpm  Label
0    82.597388      37.165500  98.394634   83.299849      0
1    79.325464      37.106323  98.832290   80.027875      0
2    84.420813      37.178937  96.849356   85.811066      0
3    74.401436      36.867330  97.164917   75.798625      0
4    76.700563      36.597646  97.465447   72.303616      0
5    79.133035      36.859964  96.185802   79.810364      0
6    64.824374      36.619367  99.795542   66.626290      0
7    67.175875      36.808107  97.980708   68.050956      0
8    72.096090      37.136524  98.650089   71.469500      0
9    83.360605      36.629398  99.100531   89.239616      0
10  123.042768      39.041669  87.015998  121.660319      1
11   72.664608      36.693199  96.661068   72.406838      0
12   77.663791      36.796381  97.173953   74.872038      0
13   83.310228      37.148411  99.659839   81.276926      0
14  133.261841      36.814615  97.483273  131.888185      1
15   81.169983      37.180198  98.886918   86.222846      0
16   65.559238      36.679248  98.842652   66.010840      0
17   73.987583      37.127035  98.253102   76.884256      0
18   84.979196      36.597532  98.159364   80.110434      0
19   51.304002      38.373140  91.649187   48.832803      1
20   71.586740      36.577036  97.708431   70.698379      0
21   76.218441      36.857523  96.888431   75.435275      0
22   94.231300      36.736331  97.292812   88.572743      0
23   89.584916      37.180247  97.007129   89.061182      0
24   72.301703      36.710615  96.147548   72.121012      0
25   95.096373      36.695053  96.958248   87.706647      0
26   93.069730      36.842617  96.968221   89.641261      0
27   76.450377      37.009751  98.529223   74.194578      0
28   64.285635      36.875042  99.341210   67.257244      0
29   80.240216      36.913625  96.066351   81.939109      0
30   78.371047      36.658547  96.697466   81.129320      0
31   78.176462      36.596265  87.038824   73.526659      1
32   64.242284      36.659985  99.928673   69.373873      0
33   79.314272      37.175794  84.407387   78.957336      1
34   89.280679      37.008169  99.548346   87.427756      0
35   91.115067      36.613140  98.425716   87.463855      0
36   82.112043      36.571030  96.020246   81.587544      0
37   66.956168      36.956373  98.848717   70.606733      0
38   84.935744      36.727780  98.598532   83.662285      0
39   77.014502      36.565572  97.060809   74.192895      0
40   78.455589      37.181107  99.568186   74.827443      0
41   78.926822      36.903833  96.780972   77.312942      0
42   64.937511      38.939889  98.581889   65.607899      1
43   77.846605      37.149823  99.866619   75.704604      0
44   65.407018      37.097107  83.490173   72.361222      1
45   87.446366      37.090949  96.281665   88.250421      0
46   70.889670      36.969800  97.016655   73.966170      0
47   44.544493      36.595635  98.211280   48.093612      1
48   63.461787      36.557116  98.511578   65.129622      0
49   79.088418      36.519332  80.467250   79.471622      1

In [10]:
new_df = df.drop('Temperature_C',axis=1)
new_df

     ECG_value       SpO2  Pulse_bpm  Label
0    82.597388  98.394634  83.299849      0
1    79.325464  98.832290  80.027875      0
2    84.420813  96.849356  85.811066      0
3    74.401436  97.164917  75.798625      0
4    76.700563  97.465447  72.303616      0
..         ...        ...        ...    ...
195  65.553363  98.721997  67.059526      0
196  90.722193  96.604232  88.771589      0
197  74.642332  97.096861  74.939860      0
198  90.203988  96.919818  87.352480      1
199  68.609210  99.474493  69.638138      0

[200 rows x 4 columns]